Introduced yml file (GitHub Action) for fastjson release
Be-Secure-Google-POC/fastjson pull request #1
Opened 2022-04-03 05:32 UTC by jobyko

Release script will 

1. Prepare the jar file. 
2. Later archive jar with requried set of files 
3. Attach the same to the release page.

Requried set of changes to be to be introduced 
1. Fix the build failure for Windows/ Mac OS.
2. Intermittent failure in tag publish in the GitHub

@asa1997  @Pranshu021 
Kindly perform a critical review

@sumodgeorge

2022-04-03 15:11 UTC, asa1997 commented
@jobyko 
- This pr has to be raised under the branch where the patch has to be released.

2022-04-03 15:11 UTC, asa1997 commented on .github/workflows/release.yml
> +      - 'v*' # Push events to  matching v*, i.e. v1.0, v20.15.10
The tag has to match our requirements.

2022-04-03 15:12 UTC, asa1997 requested changes
@jobyko Please address the comments

2022-04-03 15:17 UTC, jobyko commented on .github/workflows/release.yml
> +      - 'v*' # Push events to  matching v*, i.e. v1.0, v20.15.10
@asa1997 
Based on requirement the tag name will be like, 1.2.24-bes0.1-cve-2017-18349

Will change it.

2022-04-04 08:00 UTC, jobyko commented
Closing the PR to include the changes requested.

2022-04-04 08:00 UTC, closed without merging